"""Vendor the webfonts from Google Fonts into `assets/`.

Run manually when a font or its version should change:

    uv run python scripts/fetch_fonts.py

Downloads the woff2 files into `assets/fonts/` and writes `assets/fonts.css`
with @font-face rules pointing at them. Both are committed, so the site build
itself needs no network access and stays reproducible.
"""

from __future__ import annotations

import re
import shutil
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
FONT_DIR = ASSETS / "fonts"
FONT_CSS = ASSETS / "fonts.css"

API = "https://fonts.googleapis.com/css2"
FAMILIES = ("Inter:wght@400..700", "JetBrains+Mono:wght@400..500")

# Only Latin text appears on the site; the other subsets would be dead weight.
SUBSETS = ("latin", "latin-ext")

# Google serves woff2 only to browsers that announce support for it.
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

_BLOCK = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.DOTALL)
_FIELD = re.compile(r"([\w-]+)\s*:\s*(.*?);")
_URL = re.compile(r"url\((https://[^)]+\.woff2)\)")


def main() -> int:
    url = f"{API}?{'&'.join(f'family={family}' for family in FAMILIES)}&display=swap"
    print(f"fetching {url}")
    source = _get(url).decode("utf-8")

    faces = [face for face in _parse(source) if face["subset"] in SUBSETS]
    if not faces:
        raise SystemExit(f"no @font-face blocks for subsets {SUBSETS}; API response changed?")

    if FONT_DIR.exists():
        shutil.rmtree(FONT_DIR)
    FONT_DIR.mkdir(parents=True)

    rules = []
    for face in faces:
        filename = _filename(face)
        data = _get(face["url"])
        (FONT_DIR / filename).write_bytes(data)
        print(f"  {filename}  {len(data) / 1024:.0f} KB")
        rules.append(_rule(face, filename))

    FONT_CSS.write_text(
        "/* Generated by scripts/fetch_fonts.py — do not edit by hand. */\n\n"
        + "\n\n".join(rules)
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {FONT_CSS.relative_to(ROOT)} with {len(rules)} @font-face rules")
    return 0


def _get(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def _parse(css: str) -> list[dict[str, str]]:
    faces = []
    for subset, body in _BLOCK.findall(css):
        fields = {key: value.strip() for key, value in _FIELD.findall(body)}
        match = _URL.search(fields.get("src", ""))
        if not match:
            continue
        faces.append(
            {
                "subset": subset,
                "url": match.group(1),
                "family": fields["font-family"].strip("'\""),
                "style": fields.get("font-style", "normal"),
                "weight": fields.get("font-weight", "400"),
                "unicode_range": fields.get("unicode-range", ""),
            }
        )
    return faces


def _filename(face: dict[str, str]) -> str:
    slug = face["family"].lower().replace(" ", "-")
    return f"{slug}-{face['subset']}.woff2"


def _rule(face: dict[str, str], filename: str) -> str:
    lines = [
        "@font-face {",
        f"  font-family: '{face['family']}';",
        f"  font-style: {face['style']};",
        f"  font-weight: {face['weight']};",
        "  font-display: swap;",
        f"  src: url(fonts/{filename}) format('woff2');",
    ]
    if face["unicode_range"]:
        lines.append(f"  unicode-range: {face['unicode_range']};")
    lines.append("}")
    return "\n".join(lines)


if __name__ == "__main__":
    sys.exit(main())
